# Generated by Django 5.0.3 on 2024-06-25 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("areaname", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=300, null=True)),
                ("creationdate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="donationew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine", models.CharField(max_length=100)),
                ("tablet_con", models.CharField(max_length=6)),
                ("medi_type", models.CharField(max_length=13)),
                ("pur_date", models.DateField(null=True)),
                ("ex_date", models.DateField(null=True)),
                ("discrib", models.TextField()),
                ("medicinepic", models.FileField(null=True, upload_to="")),
                ("collectionloc", models.CharField(max_length=300, null=True)),
                (
                    "status",
                    models.CharField(default="Pending", max_length=50, null=True),
                ),
                ("adminremark", models.CharField(max_length=300, null=True)),
                ("volunteerreamrk", models.CharField(max_length=300, null=True)),
                ("donationdate", models.DateTimeField(auto_now_add=True)),
                ("updationdate", models.DateField(null=True)),
                ("name", models.CharField(max_length=20)),
                ("last", models.CharField(max_length=20)),
                ("contact", models.CharField(max_length=15)),
                ("email", models.CharField(max_length=60)),
                ("donorpic", models.FileField(null=True, upload_to="")),
                ("area", models.CharField(max_length=100, null=True)),
                ("vol_member", models.CharField(max_length=60)),
            ],
            options={
                "db_table": "donationew",
            },
        ),
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact", models.CharField(max_length=15, null=True)),
                ("address", models.CharField(max_length=300, null=True)),
                ("userpic", models.FileField(null=True, upload_to="")),
                ("regdate", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deliverypic", models.FileField(null=True, upload_to="")),
                ("creationdate", models.DateTimeField(auto_now_add=True)),
                (
                    "donation_g",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.donationew",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ngo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ngo_name", models.CharField(max_length=150, null=True)),
                ("ngo_id", models.CharField(max_length=20, null=True)),
                ("reg_no", models.CharField(max_length=20, null=True)),
                ("reg_contact", models.CharField(max_length=15, null=True)),
                ("reg_logo", models.FileField(null=True, upload_to="")),
                ("reg_proof", models.FileField(null=True, upload_to="")),
                ("address", models.CharField(max_length=300, null=True)),
                ("city", models.CharField(max_length=20, null=True)),
                ("state", models.CharField(max_length=20, null=True)),
                ("about_self", models.CharField(max_length=400, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact", models.CharField(max_length=15, null=True)),
                ("address", models.CharField(max_length=300, null=True)),
                ("userpic", models.FileField(null=True, upload_to="")),
                ("idpic", models.FileField(null=True, upload_to="")),
                ("aboutme", models.CharField(max_length=300, null=True)),
                ("status", models.CharField(max_length=20, null=True)),
                ("regdate", models.DateTimeField(auto_now_add=True)),
                ("adminremark", models.CharField(max_length=300, null=True)),
                ("updationdate", models.DateField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicinename", models.CharField(max_length=100, null=True)),
                ("donationpic", models.FileField(null=True, upload_to="")),
                ("collectionloc", models.CharField(max_length=300, null=True)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(default="Pending", max_length=50, null=True),
                ),
                ("donationdate", models.DateTimeField(auto_now_add=True)),
                ("adminremark", models.CharField(max_length=300, null=True)),
                ("volunteerreamrk", models.CharField(max_length=300, null=True)),
                ("updationdate", models.DateField(null=True)),
                (
                    "donationarea",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.donationarea",
                    ),
                ),
                (
                    "donationew",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.donationew",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="service.donor"
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.volunteer",
                    ),
                ),
            ],
            options={
                "db_table": "donation",
            },
        ),
    ]
