# Generated by Django 5.0.3 on 2024-06-28 02:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Donation",
        ),
    ]
