# Generated by Django 5.0.3 on 2024-06-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_delete_donation"),
    ]

    operations = [
        migrations.AddField(
            model_name="donationew",
            name="deliverydate",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="donationew",
            name="deliverypic",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
